apiVersion: v1
kind: Secret
metadata:
  name: google-cloud
type: Opaque
data:
  gcloudapplication-credentials.json: test.json
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: google-cloud-storage-service-account
secrets:
  - name: google-cloud-storage-credentials
