apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: hello-custom
  namespace: kserve-test
spec:
  predictor:
    containers:
      - name: hello-container
        image: jacobkun/hello:v4
