apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-regex
  namespace: kserve-test
spec:
  predictor:
    containers:
      - name: regex-container
        image: jacobkun/regex-base:v5

