apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: github-sklearn-model
  namespace: kserve-test
spec:
  predictor:
    containers:
      - name: regex-container
        image: regex-container:v1
        ports:
          - containerPort: 8080