apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-sklearn-model
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: "v2"
      storageUri: gcr.io/jacob-dev-345806/boston-model